sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t yryz/safenet-etoken .

script:
  - docker images
  - docker run --rm --privileged -v /dev/bus/usb:/dev/bus/usb yryz/safenet-etoken lsusb

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
